# data parameters
smooth_num             : 3
# model parameters
model_name             : "dvae"
prior_hidden_dim1      : 300
hidden_dim1            : 300
hidden_dim2            : 100
latent_dim             : 50
alpha                  : 0.9
beta                   : 0.001
likelihood             : "poisson"

#optimizer parameters
lr                     : 0.001
weight_decay           : 0.0001

#training parameters
seed                   : 1
batch_size             : 32
epoches                : 300
patience_epoch         : 10
patience_improve_percentage : 0.01
use_cuda               : yes
use_log                : yes 
use_tensorboard        : yes
tensorboard_base_dir   : tensorboard
log_base_dir           : log 
checkpoint_base_dir    : checkpoint 
log_interval           : 10
log_header             :
        - "epoch"
        - "train_or_val"
        - "total_loss"
        - "recon_loss"
        - "kl_loss"
        - "reg_loss"
        - "reg_hat_loss" 
save_params            :
        - "data_name"
        - "fold"
        - "smooth_num"
        - "model_name"
        - "prior_hidden_dim1"
        - "hidden_dim1"
        - "hidden_dim2"
        - "latent_dim"
        - "alpha"
        - "beta"
additional_params      : null
#restore parameters
save_criterias         :
        - "y_vaf"
        - "y_hat_vaf"
        - "y_mean_vaf"
        - "y_cc"
        - "y_rmse"
        - "loss"
        - "x_lik"
        - "x_rmse"
        - "x_vaf"
save_xhat_res          : yes
